<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert([
            [
                'food_name'   => 'むすびランチ',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '330',
            ],
            [
                'food_name'   => '鉄板ハンバーグランチ',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '560',
            ],
            [
                'food_name'   => '鉄板旨辛グリルチキンランチ',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '560',
            ],
            [
                'food_name'   => '日替わりオムライス',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '460',
            ],
            [
                'food_name'   => '週替わり丼',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '460',
            ],
            [
                'food_name'   => '週替わりパスタ',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '460',
            ],
            [
                'food_name'   => '唐マヨ丼',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '390',
            ],
            [
                'food_name'   => 'メガ唐マヨ丼',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '490',
            ],
            [
                'food_name'   => 'タレカツ丼',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '390',
            ],
            [
                'food_name'   => 'メガタレカツ丼',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '490',
            ],
            [
                'food_name'   => '味噌カツ丼',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '400',
            ],
            [
                'food_name'   => 'メガ味噌カツ丼',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '500',
            ],
            [
                'food_name'   => '本日のサラダ',
                'store_name'  => 'musubi',
                'store_jname' => 'むすびキッチン',
                'price'       => '150~',
            ],
            [
                'food_name'   => '油そば',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '300',
            ],
            [   'food_name'   => '京都背脂らーめん',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '470',
            ],
            [
                'food_name'   => '鶏塩白湯らーめん',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '500',
                'food_img'    => 'itibariki/food<1>.jpg',
            ],
            [
                'food_name'   => '濃厚魚介つけめん(大盛サービス)',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '650',
            ],
            [
                'food_name'   => '塩油そば',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '300',
            ],
            [
                'food_name'   => 'チャーシュー油そば',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '420',
            ],
            [
                'food_name'   => 'ピリもや油そば',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '420',
            ],
            [
                'food_name'   => '油そばライト',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '380',
                'food_img'    => 'itibariki/food<2>.jpg',
            ],
            [
                'food_name'   => '温泉卵',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '50',
            ],
            [
                'food_name'   => '味玉',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '80',
            ],
            [
                'food_name'   => 'チャーシュー',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '120',
            ],
            [
                'food_name'   => 'ごはん',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '110',
            ],
            [
                'food_name'   => 'たまごかけごはん',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '160',
            ],
            [
                'food_name'   => '気まぐれ丼',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '250',
                'food_img'    => 'itibariki/food<3>.jpg',
            ],
            [
                'food_name'   => 'からあげ',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '150',
            ],
            [
                'food_name'   => '大盛',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '60',
            ],
            [
                'food_name'   => 'テイクアウト各種セット',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '300~',
            ],
            [
                'food_name'   => '鶏白湯魚介らーめん',
                'store_name'  => 'itibariki',
                'store_jname' => 'らーめん壱馬力',
                'price'       => '520',
            ],
            [
                'food_name'   => '週替りランチ',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '440',
            ],
            [
                'food_name'   => 'ふじカツ',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '460',
            ],
            [
                'food_name'   => 'ふじカツ(味噌汁付)',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '490',
                'food_img'    => 'fujikatu/food<1>.jpg',
            ],
            [
                'food_name'   => 'ジャンカツ',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '460',
            ],
            [
                'food_name'   => 'ジャンカツ(味噌汁付)',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '490',
                'food_img'    => 'fujikatu/food<2>.jpg',
            ],
            [
                'food_name'   => '一口ヒレカツ',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '440',
            ],
            [
                'food_name'   => '黒豚ミンチカツ',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '440',
            ],
            [
                'food_name'   => '白身カツ',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '420',
            ],
            [
                'food_name'   => '牛肉男爵コロッケ',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '430',
            ],
            [
                'food_name'   => 'ミックスフライ',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '430',
            ],
            [
                'food_name'   => '若鶏の甘酢タルタルソース',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '460',
            ],
            [
                'food_name'   => '若鶏の甘酢タルタルソース(味噌汁付)',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '490',
                'food_img'    => 'fujikatu/food<3>.jpg',
            ],
            [
                'food_name'   => 'ハーフ&ハーフカツ',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '460',
            ],
            [
                'food_name'   => 'ふじカツおろしポン酢',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '470',
            ],
            [
                'food_name'   => 'ふじカツ味噌ソース',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '470',
            ],
            [
                'food_name'   => 'ジャンカツおろしポン酢',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '470',
            ],
            [
                'food_name'   => 'ジャンカツ味噌ソース',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '470',
            ],
            [
                'food_name'   => '一口ヒレカツおろしポン酢',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '440',
            ],
            [
                'food_name'   => '一口ヒレカツ味噌ソース',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '440',
            ],
            [
                'food_name'   => '味噌汁',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '30',
            ],
            [
                'food_name'   => 'ご飯大盛(+100g)',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '90',
            ],
            [
                'food_name'   => 'ご飯特盛(+200g)',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '160',
            ],
            [
                'food_name'   => 'おろしポン酢',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '30',
            ],
            [
                'food_name'   => '激辛ソース',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '30',
            ],
            [
                'food_name'   => '味噌ソース',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '30',
            ],
            [
                'food_name'   => 'キャベツ大盛',
                'store_name'  => 'fujikatu',
                'store_jname' => 'ふじカツ',
                'price'       => '30',
            ],
            [
                'food_name'   => 'かけうどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '200',
                'food_img'    => 'miyako/food<1>.jpg',
            ],
            [
                'food_name'   => 'ぶっかけうどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '200',
            ],
            [
                'food_name'   => '釜玉うどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '260',
            ],
            [
                'food_name'   => 'カレーうどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '290',
            ],
            [
                'food_name'   => 'きつねうどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '260',
                'food_img'    => 'miyako/food<6>.jpg',
            ],
            [
                'food_name'   => 'わかめうどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '230',
            ],
            [
                'food_name'   => 'おろしうどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '260',
            ],
            [
                'food_name'   => '明太うどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '290',
            ],
            [
                'food_name'   => '明太釜玉うどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '320',
            ],
            [
                'food_name'   => '肉うどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '360',
            ],
            [
                'food_name'   => '肉釜玉うどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '320',
            ],
            [
                'food_name'   => 'のり玉ぶっかけうどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '280',
                'food_img'    => 'miyako/food<5>.jpg',
            ],
            [
                'food_name'   => '月見とろろうどん',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '310',
            ],
            [
                'food_name'   => '麺大盛り(1玉追加)',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '80',
            ],
            [
                'food_name'   => 'かぼちゃ天',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '90',
                'food_img'    => 'miyako/food<2>.jpg',
            ],
            [
                'food_name'   => 'なす天',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '90',
            ],
            [
                'food_name'   => '鶏天',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '120',
            ],
            [
                'food_name'   => 'サツマイモ天',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '90',
                'food_img'    => 'miyako/food<2>.jpg',
            ],
            [
                'food_name'   => 'かき揚げ',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '100',
                'food_img'    => 'miyako/food<2>.jpg',
            ],
            [
                'food_name'   => 'ちくわ天',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '100',
            ],
            [
                'food_name'   => '串からあげ',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '100',
            ],
            [
                'food_name'   => '半熟玉子天',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '100',
            ],
            [
                'food_name'   => '納豆',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '50',
            ],
            [
                'food_name'   => '温玉',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '50',
            ],
            [
                'food_name'   => 'マヨから丼',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '380',
                'food_img'    => 'miyako/food<3>.jpg',
            ],
            [
                'food_name'   => 'BIGマヨから丼',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '430',
            ],
            [
                'food_name'   => '豚丼(並)',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '350',
            ],
            [
                'food_name'   => '豚丼(大)',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '400',
            ],
            [
                'food_name'   => 'カレーライス',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '330',
            ],
            [
                'food_name'   => 'BIGカレーライス',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '380',
            ],
            [
                'food_name'   => 'コロッケ',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '80',
            ],
            [
                'food_name'   => 'から揚げ',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '210',
            ],
            [
                'food_name'   => 'ポテトフライ',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '120',
            ],
            [
                'food_name'   => 'おにぎり(鮭)',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '100',
            ],
            [
                'food_name'   => 'おにぎり(ゆかり)',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '100',
            ],
            [
                'food_name'   => 'おにぎり(鶏天むす)',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '100',
            ],
            [
                'food_name'   => 'おにぎり(明太マヨ)',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '100',
            ],
            [
                'food_name'   => 'おにぎり(いなり)',
                'store_name'  => 'miyako',
                'store_jname' => 'MIYAKO製麺',
                'price'       => '100',
            ],
            [
                'food_name'   => 'レギュラーオムライス',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '400',
            ],
            [
                'food_name'   => 'ふわふわ帽子のオムライス',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '400',
                'food_img'    => 'babyface/food<1>.jpg',
            ],
            [
                'food_name'   => 'ハーフ&ハーフオムライス',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '450',
            ],
            [
                'food_name'   => 'イタリアンオムライス',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '450',
            ],
            [
                'food_name'   => 'チェダーホワイトオムライス',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '450',
            ],
            [
                'food_name'   => 'チーズタッカルビオムライス',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '500',
            ],
            [
                'food_name'   => '明太とろろオムライス',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '500',
            ],
            [
                'food_name'   => 'シンガポールチキン',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '500',
            ],
            [
                'food_name'   => 'ミートソース',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '400',
            ],
            [
                'food_name'   => 'カルボナーラ',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '500',
                'food_img'    => 'babyface/food<2>.jpg',
            ],
            [
                'food_name'   => 'BNTパスタ',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '450',
            ],
            [
                'food_name'   => '明太子クリーム',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '400',
            ],
            [
                'food_name'   => 'ペペロンチーノ',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '400',
            ],
            [
                'food_name'   => '生ハムトマト',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '450',
            ],
            [
                'food_name'   => 'MIXジュース',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '200',
            ],
            [
                'food_name'   => 'ミニMIXジュース',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '100',
            ],
            [
                'food_name'   => 'サラダ・スープセット',
                'store_name'  => 'babyface',
                'store_jname' => 'BABY FACE PLANETS',
                'price'       => '100',
            ],
            [
                'food_name'   => 'クロワッサン(クリームサンド)',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '150',
            ],
            [
                'food_name'   => 'コロネ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '130',
            ],
            [
                'food_name'   => '塩バターパン',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '110',
            ],
            [
                'food_name'   => 'ウィンナーロール',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '140',
            ],
            [
                'food_name'   => 'リンゴケーキデニッシュ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '140',
            ],
            [
                'food_name'   => 'ティーチョコワッサン',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '130',
            ],
            [
                'food_name'   => 'チョコワッサン',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '130',
            ],
            [
                'food_name'   => 'チョコパイ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '130',
            ],
            [
                'food_name'   => '明太フランス',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '130',
            ],
            [
                'food_name'   => 'チーズむしパン',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '100',
            ],
            [
                'food_name'   => 'メロンパン',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '120',
                'food_img'    => 'cosmic/food<1>.jpg',
            ],
            [
                'food_name'   => 'チョコチップメロンパン',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '120',
            ],
            [
                'food_name'   => 'チュロス',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '120',
            ],
            [
                'food_name'   => 'クッペサンド',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '100',
            ],
            [
                'food_name'   => 'ココアロール',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '90',
            ],
            [
                'food_name'   => 'ごま団子',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '120',
            ],
            [
                'food_name'   => '照り焼きチキン',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '140',
            ],
            [
                'food_name'   => '塩メロンパン',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '140',
            ],
            [
                'food_name'   => 'はちみつバター',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '100',
            ],
            [
                'food_name'   => 'ハムチーズドーナツ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '140',
            ],
            [
                'food_name'   => 'カレードーナツ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '130',
            ],
            [
                'food_name'   => 'ピザ風ドーナツ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '140',
            ],
            [
                'food_name'   => 'ロースカツサンド',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '280',
            ],
            [
                'food_name'   => 'デニッシュサンド',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '130',
            ],
            [
                'food_name'   => 'ホットコーヒー(神山ブレンド)',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '100',
                'food_img'    => 'cosmic/food<2>.jpg',
            ],
            [
                'food_name'   => 'アイスコーヒー',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '120',
            ],
            [
                'food_name'   => 'ホットカフェラテ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '200',
            ],
            [
                'food_name'   => 'アイスカフェラテ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '200',
            ],
            [
                'food_name'   => 'キャラメルマキアート',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '260',
            ],
            [
                'food_name'   => 'カフェモカ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '240',
            ],
            [
                'food_name'   => 'カフェモカアイス',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '240',
            ],
            [
                'food_name'   => 'キャラメルフラーペ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '300',
            ],
            [
                'food_name'   => 'モカフラーペ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '240',
            ],
            [
                'food_name'   => 'コーヒーフラーペ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '200',
            ],
            [
                'food_name'   => 'エスプレッソフラーペ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '200',
            ],
            [
                'food_name'   => 'アールグレイティー',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '120',
            ],
            [
                'food_name'   => 'ダージリンティー',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '120',
            ],
            [
                'food_name'   => 'チャイティー',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '150',
            ],
            [
                'food_name'   => 'エスプレッソ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '150',
            ],
            [
                'food_name'   => 'エスプレッソマキアート',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '150',
            ],
            [
                'food_name'   => 'メロンパンソフト',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '260',
            ],
            [
                'food_name'   => 'チュロスパフェ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '280',
            ],
            [
                'food_name'   => 'プリンパフェ',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '220',
            ],
            [
                'food_name'   => 'ソフトクリーム(小)',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '120',
                'food_img'    => 'cosmic/food<3>.jpg',
            ],
            [
                'food_name'   => 'ソフトクリーム(大)',
                'store_name'  => 'cosmic',
                'store_jname' => 'cosmic bakery cafe',
                'price'       => '200',
                'food_img'    => 'cosmic/food<3>.jpg',
            ],
            [
                'food_name'   => 'あさイチ定食',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '150',
                'food_img'    => 'libre/food<1>.jpg',
            ],
            [
                'food_name'   => '神山ランチ',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '290',
                'food_img'    => 'libre/food<6>.jpg',
            ],
            [
                'food_name'   => '日替わりランチ',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '430',
            ],
            [
                'food_name'   => '唐揚げランチ',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '430',
            ],
            [
                'food_name'   => '(昼)日替わり丼',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '420',
            ],
            [
                'food_name'   => 'チキン南蛮ランチ',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '430',
                'food_img'    => 'libre/food<7>.jpg',
            ],
            [
                'food_name'   => 'がっつりチキン南蛮ランチ',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '510',
            ],
            [
                'food_name'   => '鶏塩サラダ丼',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '430',
                'food_img'    => 'libre/food<3>.jpg',
            ],
            [
                'food_name'   => '玉子丼(S)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '250',
            ],
            [
                'food_name'   => '玉子丼(M)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '300',
            ],
            [
                'food_name'   => '玉子丼(L)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '360',
            ],
            [
                'food_name'   => '親子丼',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '370',
            ],
            [
                'food_name'   => 'かつ丼',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '410',
            ],
            [
                'food_name'   => '天津飯',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '380',
            ],
            [
                'food_name'   => 'がっつり天津飯',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '480',
            ],
            [
                'food_name'   => 'カレー(M)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '290',
            ],
            [
                'food_name'   => 'カレー(L)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '390',
            ],
            [
                'food_name'   => 'コロッケカレー',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '350',
            ],
            [
                'food_name'   => '唐揚げカレー',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '430',
            ],
            [
                'food_name'   => 'カツカレー',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '390',
            ],
            [
                'food_name'   => 'ダブルカツカレー',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '460',
                'food_img'    => 'libre/food<4>.jpg',
            ],
            [
                'food_name'   => 'ライス(S)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '130',
            ],
            [
                'food_name'   => 'ライス(M)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '160',
            ],
            [
                'food_name'   => 'ライス(L)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '190',
            ],
            [
                'food_name'   => '味噌汁',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '30',
            ],
            [
                'food_name'   => 'かけうどん・そば(S)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '100',
            ],
            [
                'food_name'   => 'かけうどん・そば(M)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '150',
            ],
            [
                'food_name'   => 'かけうどん・そば(L)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '200',
            ],
            [
                'food_name'   => 'きつねうどん・そば',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '210',
            ],
            [
                'food_name'   => 'わかめうどん・そば',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '230',
            ],
            [
                'food_name'   => '山菜うどん・そば',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '270',
            ],
            [
                'food_name'   => '天ぷらうどん・そば',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '270',
            ],
            [
                'food_name'   => '梅わかめうどん・そば',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '270',
            ],
            [
                'food_name'   => 'カレーうどん',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '270',
            ],
            [
                'food_name'   => 'かけラーメン(S)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '120',
            ],
            [
                'food_name'   => 'かけラーメン(M)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '200',
            ],
            [
                'food_name'   => 'かけラーメン(L)',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '300',
            ],
            [
                'food_name'   => 'ラーメン',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '290',
            ],
            [
                'food_name'   => '唐揚ラーメン',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '360',
            ],
            [
                'food_name'   => 'デラックス中華麺',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '460',
                'food_img'    => 'libre/food<2>.jpg',
            ],
            [
                'food_name'   => '(夜)日替り定食',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '430',
                'food_img'    => 'libre/food<9>.jpg',
            ],
            [
                'food_name'   => '(夜)ふじカツのふじカツ',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '460',
            ],
            [
                'food_name'   => '(夜)ふじカツのジャンカツ',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '460',
                'food_img'    => 'libre/food<11>.jpg',
            ],
            [
                'food_name'   => '(夜)ふじカツの若鶏甘酢タルタル',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '460',
            ],
            [
                'food_name'   => '(夜)なごみ亭のタレカツ丼',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '390',
                'food_img'    => 'libre/food<10>.jpg',
            ],
            [
                'food_name'   => '(夜)なごみ亭のメガタレカツ丼',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '490',
            ],
            [
                'food_name'   => '(夜)なごみ亭の唐マヨ丼',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '390',
                'food_img'    => 'libre/food<5>.jpg',
            ],
            [
                'food_name'   => '(夜)なごみ亭のメガ唐マヨ丼',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '490',
            ],
            [
                'food_name'   => '(夜)なごみ亭のギガタレカツ丼',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '560',
            ],
            [
                'food_name'   => '(夜)なごみ亭のギガ唐マヨ丼',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '560',
            ],
            [
                'food_name'   => '(夜)カツカレー',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '390',
            ],
            [
                'food_name'   => '(夜)ダブルカツカレー',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '460',
            ],
            [
                'food_name'   => '(夜)ギガカツカレー',
                'store_name'  => 'libre',
                'store_jname' => 'LIBRE（リブレ）',
                'price'       => '560',
            ],
            [
                'food_name'   => '日替りランチ',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '420',
            ],
            [
                'food_name'   => '日替りランチ・ライス小・デザート付',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '420',
            ],
            [
                'food_name'   => '鶏唐揚げ',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '270',
            ],
            [
                'food_name'   => '焼き肉',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '270',
            ],
            [
                'food_name'   => '鶏唐揚げ&焼き肉',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '270',
            ],
            [
                'food_name'   => 'おかず大盛',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '120',
            ],
            [
                'food_name'   => 'ライス(特大)',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '180',
            ],
            [
                'food_name'   => 'ライス(大)',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '140',
            ],
            [
                'food_name'   => 'ライス(中)',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '120',
            ],
            [
                'food_name'   => 'ライス(小)',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '80',
            ],
            [
                'food_name'   => 'たきこみご飯(中)',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '140',
            ],
            [
                'food_name'   => 'たきこみご飯(小)',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '100',
                'food_img'    => 'hannnari/food<2>.jpg',
            ],
            [
                'food_name'   => '日替り丼',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '420',
            ],
            [
                'food_name'   => '鶏唐揚てりマヨ丼',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '400',
            ],
            [
                'food_name'   => '鶏唐揚てりマヨ丼(ミニ)',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '220',
            ],
            [
                'food_name'   => '焼き肉丼',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '370',
            ],
            [
                'food_name'   => '焼き肉丼(ミニ)',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '200',
            ],
            [
                'food_name'   => 'チキン竜田丼',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '370',
            ],
            [
                'food_name'   => 'チキン竜田丼(ミニ)',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '200',
            ],
            [
                'food_name'   => '鶏玉子丼',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '370',
            ],
            [
                'food_name'   => '鶏玉子丼(ミニ)',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '200',
            ],
            [
                'food_name'   => 'カレー',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '270',
            ],
            [
                'food_name'   => '鶏唐揚げカレー',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '400',
            ],
            [
                'food_name'   => 'ミニカレー',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '180',
            ],
            [
                'food_name'   => 'ご飯大盛',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '80',
            ],
            [
                'food_name'   => '日替り麺',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '320',
            ],
            [
                'food_name'   => 'きつねうどん・そば',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '210',
            ],
            [
                'food_name'   => 'わかめうどん・そば',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '210',
            ],
            [
                'food_name'   => 'カレーうどん・そば',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '250',
            ],
            [
                'food_name'   => '肉うどん・そば',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '280',
                'food_img'    => 'hannnari/food<2>.jpg',
            ],
            [
                'food_name'   => '醤油ラーメン',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '300',
            ],
            [
                'food_name'   => 'とんこつラーメン',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '300',
            ],
            [
                'food_name'   => '肉ラーメン',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '380',
            ],
            [
                'food_name'   => '半玉増量',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '50',
            ],
            [
                'food_name'   => '小鉢',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '80',
            ],
            [
                'food_name'   => 'ミニサラダ',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '100',
            ],
            [
                'food_name'   => 'みそ汁',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '50',
            ],
            [
                'food_name'   => 'デザート',
                'store_name'  => 'hannnari',
                'store_jname' => 'はんなり食堂',
                'price'       => '80',
            ],
            [
                'food_name'   => '松華堂弁当',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '540',
                'food_img'    => 'furusato/food<1>.jpg',
            ],
            [
                'food_name'   => '日替り定食',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '540',
                'food_img'    => 'furusato/food<2>.jpg',
            ],
            [
                'food_name'   => '出し巻定食',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '540',
            ],
            [
                'food_name'   => '鍋焼きうどん',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '490',
            ],
            [
                'food_name'   => 'かき揚げそば',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '450',
            ],
            [
                'food_name'   => 'にしんそば',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '450',
            ],
            [
                'food_name'   => '肉カレーラーメン',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '480',
            ],
            [
                'food_name'   => '野菜ラーメン',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '450',
                'food_img'    => 'furusato/food<3>.jpg',
            ],
            [
                'food_name'   => '甘きつねうどん',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '430',
            ],
            [
                'food_name'   => '肉うどん',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '450',
            ],
            [
                'food_name'   => '肉カレーうどん',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '480',
            ],
            [
                'food_name'   => 'カレーうどん',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '380',
            ],
            [
                'food_name'   => 'サラダ風冷麺',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '490',
            ],
            [
                'food_name'   => '天ざるそば',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '450',
            ],
            [
                'food_name'   => 'カツカレーライス',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '570',
            ],
            [
                'food_name'   => '魚フライランチ',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '650',
            ],
            [
                'food_name'   => 'チキンカツランチ',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '650',
            ],
            [
                'food_name'   => 'ビーフカレーライス',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '460',
            ],
            [
                'food_name'   => 'チキンカレーライス',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '460',
            ],
            [
                'food_name'   => 'とり丼',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '540',
            ],
            [
                'food_name'   => 'むすびわざ丼',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '540',
            ],
            [
                'food_name'   => 'テイクアウト丼',
                'store_name'  => 'furusato',
                'store_jname' => 'ラウンジふるさと',
                'price'       => '340',
            ],
        ]);
    }
}
